### ISSUE TITLE
"\n" in property value is transformed to a new line in the result

### ISSUE THREAD

**Issue by adorjan** [tmoreira2020/portal-properties-prettier-app#5]
From
ldap.group.mappings.0=groupName=cn\ndescription=description\nuser=uniqueMember
It creates
ldap.group.mappings.0=groupName=cn
description=description
user=uniqueMember

**Comment by tmoreira2020** [comment]
I released a new version yesterday, take a look at the online version if it fixes the issue.

**Comment by adorjan** [comment]
It works correctly, I can no longer reproduce the issue.
Thanks, Thiago!
